GET http://localhost:3000/api/user
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE1ODM5NTQ2MzR9.QWocb6CN-rtHzztreVBI1GW2D7kgobLfP3eJa_QBQfo

###

POST http://localhost:3000/api/user
Accept: application/json
Content-Type: application/json

{
  "user": {
    "email": "user1@example.com",
    "password": "password",
    "first_name": "first_name",
    "last_name": "last_name",
    "birthday": "20.10.1995"
  }
}

###

PUT http://localhost:3000/api/user
Accept: application/json

###

DELETE http://localhost:3000/api/user
Accept: application/json

###

POST http://localhost:3000/auth
Accept: application/json
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "password"
}

###
GET http://localhost:3000/auth
Accept: application/json
Content-Type: application/json

###
