GET http://localhost:3000/api/user
Accept: application/json

###

POST http://localhost:3000/api/user
Accept: application/json
Content-Type: application/json

{
  "user": {
    "email": "user1@example.com",
    "password": "password",
    "first_name": "first_name",
    "last_name": "last_name",
    "birthday": "20.10.1995"
  }
}

###

PUT http://localhost:3000/api/user
Accept: application/json

###

DELETE http://localhost:3000/api/user
Accept: application/json

###
